data_install=xlsread('stacked-bar.xlsx',1,'B2:I18');
data_run=xlsread('stacked-bar.xlsx',2,'B2:I12');

%draw install total stacked bar(without emulator 27)
figure;
DELETE_FAILED_INTERNAL_ERROR=data_install(1,:)';
INSTALL_FAILED_DUPLICATE_PERMISSION=data_install(2,:)';
INSTALL_FAILED_INSUFFICIENT_STORAGE=data_install(3,:)';
INSTALL_FAILED_INTERNAL_ERROR=data_install(4,:)';
INSTALL_FAILED_INVALID_APK=data_install(5,:)';
INSTALL_FAILED_MISSING_SHARED_LIBRARY=data_install(6,:)';
INSTALL_FAILED_NO_MATCHING_ABIS=data_install(7,:)';
INSTALL_FAILED_OLDER_SDK=data_install(8,:)';
INSTALL_FAILED_VERSION_DOWNGRADE=data_install(9,:)';
INSTALL_PARSE_FAILED_BAD_MANIFEST=data_install(10,:)';
INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME=data_install(11,:)';
INSTALL_PARSE_FAILED_BAD_SHARED_USER_ID=data_install(12,:)';
INSTALL_PARSE_FAILED_MANIFEST_MALFORMED=data_install(13,:)';
INSTALL_PARSE_FAILED_NO_CERTIFICATES=data_install(14,:)';
INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION=data_install(15,:)';
NO_MESSAGE=data_install(16,:)';
bar(2010:2017,[DELETE_FAILED_INTERNAL_ERROR INSTALL_FAILED_DUPLICATE_PERMISSION INSTALL_FAILED_INSUFFICIENT_STORAGE INSTALL_FAILED_INTERNAL_ERROR INSTALL_FAILED_INVALID_APK INSTALL_FAILED_MISSING_SHARED_LIBRARY INSTALL_FAILED_NO_MATCHING_ABIS INSTALL_FAILED_OLDER_SDK INSTALL_FAILED_VERSION_DOWNGRADE INSTALL_PARSE_FAILED_BAD_MANIFEST INSTALL_PARSE_FAILED_BAD_PACKAGE_NAME INSTALL_PARSE_FAILED_BAD_SHARED_USER_ID INSTALL_PARSE_FAILED_MANIFEST_MALFORMED INSTALL_PARSE_FAILED_NO_CERTIFICATES INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION NO_MESSAGE],0.5,'stack');

%ytickformat(axes, 'percentage');

xlabel('year');
ylabel('failure rate');
legend('DELETE FAILED INTERNAL ERROR','INSTALL FAILED DUPLICATE PERMISSION','INSTALL FAILED INSUFFICIENT STORAGE','INSTALL FAILED INTERNAL ERROR','INSTALL FAILED INVALID APK','INSTALL FAILED MISSING SHARED LIBRARY','INSTALL FAILED NO MATCHING ABIS','INSTALL FAILED OLDER SDK','INSTALL FAILED VERSION DOWNGRADE','INSTALL PARSE FAILED BAD MANIFEST','INSTALL PARSE FAILED BAD PACKAGE NAME','INSTALL PARSE FAILED BAD SHARED USER ID','INSTALL PARSE FAILED MANIFEST MALFORMED','INSTALL PARSE FAILED NO CERTIFICATES','INSTALL PARSE FAILED UNEXPECTED EXCEPTION','NO MESSAGE');

%draw run time total stacked bar
data_run=data_run';
Activity=data_run(:,1);
Illegal=data_run(:,2);
IO=data_run(:,3); 
lang=data_run(:,4);
Native=data_run(:,5);
Class=data_run(:,6);
message=data_run(:,7);
Null=data_run(:,8); 
Security=data_run(:,9);
Unatisfied=data_run(:,10); 
Verify=data_run(:,11); 

figure;
bar(2010:2017,[Activity Illegal IO lang Native Class message Null Security Unatisfied Verify],0.5,'stack');
xlabel('year');
ylabel('failure rate');
legend('Activity not found','Illegal monitor','IO exception','lang.error','Native Crash','No Class','No message','Null Pointer','Security','Unatisfied link','Verify error');
